### PR TITLE
async version experiment

### PR DESCRIPTION
**Pull request by sinisaos**
Experimented with the async  version pagination.

### CODE REVIEW

**Comment by dantownsend** [comment]
Thanks - I'll give this a go tomorrow

**Comment by dantownsend** [comment]
The problem is in `decode_cursor` - there's still a `run_sync`. If you make it async, it should work.

**Comment by dantownsend** [comment]
I think this can be changed:

https://github.com/piccolo-orm/piccolo_cursor_pagination/blob/5e7151da924d14ef9a4562a4393b525fde9e6f5c/example/app.py#L44-L49

FastAPI gives you the `__cursor` as a function argument, so there's no need to read it from the request.

I would make `__cursor: t.Optional[str]` too.

**Comment by sinisaos** [comment]
> The problem is in `decode_cursor` - there's still a `run_sync`. If you make it async, it should work.

Great. You're right. With this change we no longer have to provide `max_size` argument in `start_connection_pool` and everything works great in all Piccolo versions. Thanks.

**Comment by sinisaos** [comment]
> I think this can be changed:
> 
> https://github.com/piccolo-orm/piccolo_cursor_pagination/blob/5e7151da924d14ef9a4562a4393b525fde9e6f5c/example/app.py#L44-L49
> 
> FastAPI gives you the `__cursor` as a function argument, so there's no need to read it from the request.

You’re right, but unfortunately if we only use function arguments, we get a weird order of results because we can go both directions (it’s a lot easier if we just go forward, and this part was the hardest for me to understand and implement).We should leave that as is for now, so maybe we’ll come up with something later.

**UPDATE**: You are right. My mistake. In my attempt, I accidentally removed the `__previous` argument and that is why the order in the rows was wrong. I will remove `cursor = request.query_params["__cursor"]`.

> I would make `__cursor: t.Optional[str]` too.

I think we should leave this as is. I think if we make this optional, it would be a problem because if we don’t give a blank initial cursor (like this `http://localhost:8000/tasks/?__cursor=`), we will get all the results that will be a problem in a large datasets.

**Comment by sinisaos** [comment]
In the future, I also thought to expand the `tasks` method in the example app by providing `first_row` and `last_row` in the request body so that the client app knows when there are no more results in both directions.
```
{
  "rows": [
       ...
   ],
 "first_row": true, <- we know there is no results any more and e.g we can hide previous button
 "last_row: false,
}
```
or 
```
{
  "rows": [
       ...
   ],
 "first_row": false, 
 "last_row: true, <- we know there is no results any more and e.g we can hide next button
}
```
What do you think? Do you think this is a good idea or should we leave it to the user to apply the client side.

**Comment by dantownsend** [comment]
> In the future, I also thought to expand the `tasks` method in the example app by providing `first_row` and `last_row` in the request body so that the client app knows when there are no more results in both directions.

It's up to you - I can see the value in it. Depends if there's much of a performance / complexity hit. You could add it as a header too.

> I think we should leave this as is. I think if we make this optional, it would be a problem because if we don’t give a blank initial cursor (like this http://localhost:8000/tasks/?__cursor=), we will get all the results that will be a problem in a large datasets.

It confused me in the Swagger UI doing this:

Screenshot 2022-04-11 at 22 27 55

Do you think this is OK? Or what about passing a cursor of 'start' or something?

I think this PR should be merged and released, and then create some separate issues. Do you want to try merging and releasing tomorrow?

**Comment by sinisaos** [comment]
Now I understand. We can provide `__cursor: t.Optional[str] = None` by adding this 
```python
async def decode_cursor(self, cursor: str, table: t.Type[Table]) -> int:
    if cursor is None: # preventing AttributeError
        cursor = ""
    base64_bytes = cursor.encode("ascii")
    cursor_bytes = base64.b64decode(base64_bytes)
    ...
```
With this change, we don’t have to put an empty string as initial cursor in the Swagger UI. What do you think?

**Comment by sinisaos** [comment]
I merged this. How to release it in PyPI? Do I need to bump version into a separate commit and everything will work automatically or? Sorry to bother you, but I’ve never done that before and I don’t want to do something wrong. Thanks.

**Comment by dantownsend** [comment]
@sinisaos If you push a new commit to master which increases the version number in setup.py, then create a release here:

https://github.com/piccolo-orm/piccolo_cursor_pagination/releases

**Comment by sinisaos** [comment]
Thanks again. Just one more question. From where I need to attach binaries? Or this binaries would be attached automatically from release script from github actions https://github.com/piccolo-orm/piccolo_cursor_pagination/blob/e600144e8d0744c3f0ee8f005a340ae1cf6b366c/.github/workflows/release.yaml#L21
Sorry again but I must ask.

**Comment by dantownsend** [comment]
@sinisaos When you create a release it automatically zips up the code and attaches it to the release - at least that's how it works with the main Piccolo repo.

**Comment by sinisaos** [comment]
@dantownsend I probably messed something up because release  to PyPI is failed. I know: because I forked this repository I push commit to main branch of fork version and because that is failed. Can you please do this properly and do this in future. Sorry again and thanks again.

**Comment by dantownsend** [comment]
@sinisaos It's fine - I think the version wasn't updated in setup.py. I'll delete the release and try again.

**Comment by dantownsend** [comment]
There we go - it's released now.

**Comment by sinisaos** [comment]
Great. I installed a new version and everything is fine. Sorry for mess and thanks.

**Comment by dantownsend** [comment]
No worries - it's all a learning experience. I only learned how to do it fairly recently.

**Pull request merged**
